version: "3"

services: 
    label-studio:
        container_name: label-studio
        image: heartexlabs/label-studio:0.7.5rc5
        ports: ["8080:8080"]
        environment:
            HOST: hostip
            PORT: 8080
            PROTOCOL: http://
            USERNAME: usernmae
            PASSWORD: pass
        volumes: ["labelstudio:/label-studio/my_project"]
        restart: always

volumes:
        labelstudio:
